export const PATHS = {
  SHARED_USER: "SHARED_USER",
  SHARED_FOLDER: "SHARED_FOLDER",
  SHARED_FOLDERNAME: "SHARED_FOLDERNAME",
  FOLDER_USER: "FOLDER_USER",
  FOLDER_CATEGORY: "FOLDER_CATEGORY",
  FOLDER_LINKS: "FOLDER_LINKS",
  DEFAULT: "DEFAULT",
} as const;
