import Head from "next/head";
import Share from "./shared/ShareContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*랜딩페이지 구현 전까지 공유페이지 보여주기*/}
      <Share />
    </>
  );
}
