// Generated by https://quicktype.io

// export interface CardData {
//   id: number;
//   created_at: string;
//   name: string;
//   user_id: number;
//   link: Link;
// }

// interface Link {
//   count: number;
// }
// Generated by https://quicktype.io

export interface ICardData {
  id: number;
  created_at: string;
  updated_at: null;
  url: string;
  title: string;
  description: string;
  image_source: string;
  folder_id: number;
}

export interface ICardContainerProps {
  showTitle: boolean;
  cardListData: ICardData[];
  cardTitleText: string;
}

// Generated by https://quicktype.io

// export interface Aa {
//   data: Datum[];
// }

// interface Datum {
//   id: number;
//   created_at: string;
//   name: string;
//   user_id: number;
//   link: Link;
// }

// interface Link {
//   count: number;
// }
// Generated by https://quicktype.io

// export interface Aa {
//   data: Datum[];
// }

// export interface Datum {
//   id:           number;
//   created_at:   string;
//   name:         string;
//   image_source: string;
//   email:        string;
//   auth_id:      string;
// }
